meta:
  title: "Jeff Hilnbrand"
  description: "I like making cool things with cool people. Product Designer at Facebook. Previously at Minimill, Autodesk, Venmo, Startup Shell, Bitcamp."
  facebook_image: "/img/jhilnbrand.jpg"
  twitter_image: "/img/jhilnbrand.jpg"
  image: "/img/jhilnbrand.jpg"
  twitter_handle: "@jhilmd"
  domain: "jhil.co"
  url: "http://jhil.co"
  google_analytics_id: "UA-46817894-1"
  theme_color: "#888888"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jhil.co" # the base hostname & protocol for your site
permalink: /:title/ # example: http://jhil.co/bitcamp

i: "/img/{{ page.url | slugify }}"

name: "Jeff Hilnbrand"
markdown: kramdown
highlighter: pygments
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - LICENSE.md

webrick:
  headers:
    Access-Control-Allow-Origin: "*"