meta:
  title: "Jeff Hilnbrand"
  description: "I like making cool things with cool people. Product Designer at Facebook. Previously at Minimill, Startup Shell, Bitcamp, Autodesk, Venmo."
  facebook_image: "/img/jhilnbrand.jpg"  # /img/facebook.png
  twitter_image: "/img/jhilnbrand.jpg"  # /img/twitter.png
  image: "/img/jhilnbrand.jpg"  # /img/share.png
  twitter_handle: "@jhilmd"  # @minimill_co
  domain: "jhil.co"  # minimill.co
  url: "http://jhil.co"  # https://minimill.co
  google_analytics_id: "" # UA-66637918-1
  theme_color: "#666666" # #FFFFFF

name: "Jeff Hilnbrand"
markdown: redcarpt
highlighter: pygments
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - LICENSE.md
